# Generated by Django 3.0 on 2019-02-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_guia_consulta', models.DecimalField(decimal_places=0, max_digits=11)),
                ('cod_medico', models.DecimalField(decimal_places=0, max_digits=11)),
                ('nome_medico', models.CharField(max_length=255)),
                ('data_consulta', models.DateField()),
                ('valor_consulta', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
    ]
