# Generated by Django 3.0 on 2019-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='id',
        ),
        migrations.AlterField(
            model_name='consulta',
            name='cod_medico',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='data_consulta',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='nome_medico',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='numero_guia_consulta',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='valor_consulta',
            field=models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True),
        ),
        migrations.AlterModelTable(
            name='consulta',
            table='consulta',
        ),
    ]
